### ISSUE TITLE
The Reason of Offset Handling for Negative Strand Coordinates

### ISSUE THREAD

**Issue by yangzhao1230** [jzhoulab/puffin#14]
There is an offset added when handling negative strand coordinates: 
```
if strand == "-":
    offset = 1
    strand_ = "minus"
else:
    offset = 0
    strand_ = "plus"

```
From my understanding, the coordinates on the positive and negative strands should be equivalent, with the only difference being the orientation. In other projects, like [BEND](https://github.com/frederikkemarin/BEND/blob/6f5ebfc1e78d0b3088150897e49db2beb135199d/bend/io/sequtils.py#L99), they simply reverse complement the sequence without adding an offset for the negative strand.

My background in biology is limited, so I would greatly appreciate any insights or explanations on this matter. Understanding the rationale behind this implementation would help in ensuring the accurate use of genomic data in my analysis.

**Comment by junhong-huang** [comment]
Hello, I'm a student in SYSU, I see you have some doubts about puffin software, I just recently also in study the software, you can communicate with me in details by email: 1051945022@qq.com

**Comment by junhong-huang** [comment]
> There is an offset added when handling negative strand coordinates:
> 
> ```
> if strand == "-":
>     offset = 1
>     strand_ = "minus"
> else:
>     offset = 0
>     strand_ = "plus"
> ```
> 
> From my understanding, the coordinates on the positive and negative strands should be equivalent, with the only difference being the orientation. In other projects, like [BEND](https://github.com/frederikkemarin/BEND/blob/6f5ebfc1e78d0b3088150897e49db2beb135199d/bend/io/sequtils.py#L99), they simply reverse complement the sequence without adding an offset for the negative strand.
> 
> My background in biology is limited, so I would greatly appreciate any insights or explanations on this matter. Understanding the rationale behind this implementation would help in ensuring the accurate use of genomic data in my analysis.

Hello, I'm a student in SYSU, I see you have some doubts about puffin software, I just recently also in study the software, you can communicate with me in details by email: 1051945022@qq.com

**Comment by jzthree** [comment]
This is due to how the transcription start site is annotated in our files. Offset is needed to make sure that the transcription start site is at the same position in the sequence no matter whether it is on "+" or "-" strand.

**Comment by junhong-huang** [comment]
您好，感谢您的来信，我会尽快查看祝身体健康，生活愉快    黄钧鸿华南师范大学生命科学学院school of life science ,SCNU&
