### ISSUE TITLE
Process_models.ipynb

### ISSUE THREAD

**Issue by junhong-huang** [jzhoulab/puffin#16]
Dear Professor Zhou,

I hope this message finds you well.

I am writing to seek assistance with an issue I encountered during the processing of our trained models. I have utilized the dataset FANTOM_CAT.lv3_robust.tss.sortedby_fantomcage.hg38.v5.highconf.tsv along with the corresponding 10 bedGraph files (e.g., agg.plus.bw.bedgraph.bw) for training purposes.

I have successfully trained the models using the script train_puffin_stage1.py, which generated 12 model files named puffin_stage1_rep0.pth through puffin_stage1_rep11.pth (numbered 0 to 11). However, upon attempting to process these models using the Jupyter Notebook Process_models.ipynb, I encountered an error:

"Traceback (most recent call last):

  File "/home/heyx/very_important_do_not_delete/puffin/fetch_stage_1_model_consensus_motifs_and_inrs.py", line 209, in <module>
    np.save(arr=np.stack(selectmats)[np.array([0, 1, 2, 4, 8, 9, 10, 11, 5, 6]),:],
  File "<__array_function__ internals>", line 180, in stack
  File "/home/heyx/anaconda3/envs/HDRNet/lib/python3.10/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack"

Interestingly, when I used the pre-provided puffin_stage1_rep0.pth models (numbered 0-11) directly from the resource, the Process_models.ipynb notebook executed successfully without any issues.

I am curious about the reason for this difference in outcomes and would like to understand what might be causing the error when processing my own trained models. Could you provide some insight or suggest what I might need to check or modify?

Your expertise and advice would be greatly appreciated.

**Comment by jzthree** [comment]
Looks like your selectmats are empty, which seems to be due to that it didn't select similar motifs among the trained models. You should inspect your trained models and also make sure that you train for long enough so that you see well characterized motifs. The notebook also needs some modification such as motif indices selected if you are training new models since the motif orders will not be the same.
