### ISSUE TITLE
Confused about the output file, didn't match the explanation

### ISSUE THREAD

**Issue by XuanrZhang** [jzhoulab/puffin#3]
HI @KseniiaDundyk,

Thanks for the tool development.

I‘ve tried to understand the puffin output by running "python puffin.py coord chr7:5529775-5531425-"

I've got an output file, which includes 80 rows in total. That didn't match your instruction of the CSV output file.

I found five rows, starting with 'sum' (not 4 in the instruction); maybe the last 36 rows are for the base contribution score, referring to 9 motifs for both strands instead of a total of 40 rows in the instruction.

Could you please have a look?

Best,
Xuan

**Comment by KseniiaDundyk** [comment]
Hi Xuan,

Thank you for bringing this issue to our attention. We have made the updates to both the code and the description of the output file, ensuring that they are now consistent with each other. 

I apologize for any confusion caused. Please let us know if you have any further questions or encounter any more issues.

Best regards,
Kseniia
