### ISSUE TITLE
puffin_D.pth missing

### ISSUE THREAD

**Issue by evin-padhi** [jzhoulab/puffin#6]
Hi,

Thanks for all your work on this great tool! Very excited about using this in my own work. I have been trying to use PuffinD, however, it seems that the `puffin_D.pth` is missing from the resources folder on the GitHub. Is the model being released soon? 

Thank you!

**Comment by KseniiaDundyk** [comment]
Hi, thank you for your interest in our work.

You need to download the `puffin_D.pth` from Zenodo and move it to the resources folder:
```
wget https://zenodo.org/record/7941729/files/puffin_D.pth
mv puffin_D.pth ./resources
```
