### ISSUE TITLE
Normalize the activation and effect scores

### ISSUE THREAD

**Issue by docmab23** [jzhoulab/puffin#8]
First of all, congrats on the great work.

So, I am using puffin to compare a class of genomic regions with other regions, I made a heatmap to get the average score of the genomic region (mean of the activations across each base pair in that region). And this is done for all motif effect and activation scores (CREB, NRF1, etc). But I want to compare these activation scores across each other, for example comparinf CREB+ with SP+, do you think normalizing the scores is a good idea, so that they are comparable. Because the interpretation changes completely, I am asking this, because distribution of the different activation and effect scores across the regions is very different.

So, is it better to compare raw activation and effect values across each other, or normalize them.

Thanks

**Comment by KseniiaDundyk** [comment]
Thank you for your kind words!

It's difficult to say if motif activations and motif effects are directly comparable across motifs. The Puffin model incorporates a feature (softplus activation function applied at the first layer) that may make motif activation somewhat comparable, but this is not certain. One approach to address this is to use a score that includes motif activation X motif effect, as this value would be comparable. For instance, if you know that the transcription initiation window is located at the center of the input sequence, you can compare the "Basepair contribution score to transcription initiation per motif" (or alternatively you can use "Motif contribution score" from the paper if you only need TSS-level scores).

Best,
Kseniia Dudnyk

**Comment by docmab23** [comment]
Thank you so much for your suggestion, Kseniia, I will definately try to incorporate it.

Best,
Mannan
